### ISSUE TITLE
`fopen` does not return a file descriptor

### ISSUE THREAD

**Issue by br0ns** [onlineta/ark15#6]
It is mentioned in [G1](https://github.com/onlineta/ark15/blob/master/g-assignments/1st/g1.asciidoc#341-opening-and-closing-files) that `fopen` returns a _file descriptor_.  That is not correct:  `fopen` returns a _file stream_.

See [Glibc: Streams and File Descriptors](http://www.gnu.org/software/libc/manual/html_node/Streams-and-File-Descriptors.html) for details.

**Comment by oleks** [comment]
Eh, yes. That's silly.
