### ISSUE TITLE
shamt before funct?

### ISSUE THREAD

**Issue by nikolajvonholck** [onlineta/ark15#8]
Shouldn't shamt be before funct in section 3.6.3 in G1? :)

**Comment by oleks** [comment]
Yes.

**Comment by nikolajvonholck** [comment]
Perhaps you should consider updating the order of the Macros listed just below, too :)

**Comment by oleks** [comment]
Yes, I noticed that just a moment later: c50bf4d4e0ec086388302c4568380c4d4cb0f37d :+1:
